typography_spectrum: 0.3608056455850601
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.2875822053756565
  lightness: 0.9347693440504372
  saturation: 0.958347684238106
  rhythmicContrast: 0.19057315471582115
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25804
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Wouter Timmermans
  email: wouter@woutertimmermans.nl
  url: 'http://fullstackdev.nl'
name: Wouter Timmermans
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    id: 7c8c35d7-da2d-4dbf-bc25-3221d07fedef
    type: content
  - name: CreaTe
    url: 'http://thegrid.ai/wouter-does-create'
    type: external
favicon: null
title: Wouter Timmermans
purpose:
  - type: contact
    url: 'mailto:wouter@woutertimmermans.nl'
    label: Contact me
