typography_spectrum: 0.858266486087814
color:
  brandColors:
    - '#2c302e'
    - '#c5d0dd'
    - '#909590'
    - '#e6efe1'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25804
analytics:
  google: null
  facebook: null
  twitter: null
name: wouter
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Wouter Timmermans
purpose: []
