name: wouter
favicon: null
layout_spectrum: 0.50963
typography_spectrum: 0.858266486087814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c211b'
    - '#cedada'
    - '#0d1019'
    - '#41ea85'
    - '#49535b'
  brandStrength: 0.6561754080466926
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
