layout_spectrum: 0.825742038275106
typography_spectrum: 0.5646114994208375
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.7903594370711005
  lightness: 0.7169459583933031
  saturation: 0.9225514615930175
  rhythmicContrast: 0.408105899361746
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Wouter Timmermans
  email: wouter@woutertimmermans.nl
  url: 'http://fullstackdev.nl'
name: Wouter Timmermans
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    id: 7c8c35d7-da2d-4dbf-bc25-3221d07fedef
    type: content
  - name: CreaTe
    url: 'http://thegrid.ai/wouter-does-create'
    type: external
favicon: null
title: Wouter Timmermans
purpose:
  - type: contact
    url: 'mailto:wouter@woutertimmermans.nl'
    label: Contact me
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/55511903-cd41-4664-89c2-eaa7f3811c32.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/55511903-cd41-4664-89c2-eaa7f3811c32.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
