name: wouter
favicon: null
layout_spectrum: 0.9656884765718132
typography_spectrum: 0.2833448483143002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8940659086219966
  lightness: 0.9477980518713593
  saturation: 0.7991228078026325
  rhythmicContrast: 0.3590410032775253
purpose: []
