name: wouter
favicon: null
layout_spectrum: 0.7575085051357746
typography_spectrum: 0.858266486087814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6561754080466926
  lightness: 0.04804665665142238
  saturation: 0.2455939925275743
  rhythmicContrast: 0.004712632857263088
purpose: []
